In [1]:
import pandas as pd
import numpy as np
import os
import unidecode

pd.set_option('display.max_columns', None)

In [2]:
os.chdir('/Users/stevengeorge/Documents/Github/fpl-analysis')
FPL_DATA_PATH = 'data/external/FantasyPremierLeague/'

## 2016-17

In [3]:
pd.read_csv(FPL_DATA_PATH + '2016-17/gws/gw1.csv', encoding="ISO-8859-1").head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15T19:00:00Z,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,55,False,0,0
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,0.3,0,0,142,0,0,3,0,0,0,0.9,142,8.2,0,2016-08-13T14:00:00Z,13 Aug 15:00,0,0,15,0,0,17,0,0,0,0,1,0,1,0,13918,1,2,0,1,1,0.0,1,0,0,0,60,True,0,0
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,4.9,1,0,16,0,0,8,0,3,0,3.0,16,2.2,0,2016-08-14T15:00:00Z,14 Aug 16:00,0,0,60,0,0,9,0,0,0,0,2,0,1,0,163170,2,0,1,4,3,23.0,2,0,0,0,80,True,0,0
3,Abdoulaye_Doucour√©,0,0,0,0,0,0,0,0,0,0.0,0,0,482,0,0,7,0,0,0,0.0,482,0.0,0,2016-08-13T14:00:00Z,13 Aug 15:00,0,0,0,0,0,13,0,0,0,0,0,0,1,0,1051,0,0,0,1,1,0.0,0,0,0,0,50,False,0,0
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,0.0,0,0,80,0,0,10,0,0,0,0.0,80,0.0,0,2016-08-15T19:00:00Z,15 Aug 20:00,0,0,0,0,0,20,0,0,0,0,0,0,1,0,1243,0,0,0,1,2,0.0,0,0,0,0,55,True,0,0

In [4]:
gw_dataframe = pd.DataFrame()
for gw in range(1, 39):
    gw_data = pd.read_csv(FPL_DATA_PATH + f'2016-17/gws/gw{gw}.csv', encoding="ISO-8859-1")
    gw_data['gw'] = gw
    gw_data['season'] = '2016-17'
    gw_dataframe = gw_dataframe.append(gw_data)

In [5]:
gw_dataframe['value'] = gw_dataframe['value'] / 10

In [6]:
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].str.replace('T', ' ')
gw_dataframe['kickoff_time'] = pd.to_datetime(gw_dataframe['kickoff_time'])
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].dt.tz_convert('Europe/London')

In [7]:
gw_dataframe.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15 20:00:00+01:00,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,0.3,0,0,142,0,0,3,0,0,0,0.9,142,8.2,0,2016-08-13 15:00:00+01:00,13 Aug 15:00,0,0,15,0,0,17,0,0,0,0,1,0,1,0,13918,1,2,0,1,1,0.0,1,0,0,0,6.0,True,0,0,1,2016-17
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,4.9,1,0,16,0,0,8,0,3,0,3.0,16,2.2,0,2016-08-14 16:00:00+01:00,14 Aug 16:00,0,0,60,0,0,9,0,0,0,0,2,0,1,0,163170,2,0,1,4,3,23.0,2,0,0,0,8.0,True,0,0,1,2016-17
3,Abdoulaye_Doucour√©,0,0,0,0,0,0,0,0,0,0.0,0,0,482,0,0,7,0,0,0,0.0,482,0.0,0,2016-08-13 15:00:00+01:00,13 Aug 15:00,0,0,0,0,0,13,0,0,0,0,0,0,1,0,1051,0,0,0,1,1,0.0,0,0,0,0,5.0,False,0,0,1,2016-17
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,0.0,0,0,80,0,0,10,0,0,0,0.0,80,0.0,0,2016-08-15 20:00:00+01:00,15 Aug 20:00,0,0,0,0,0,20,0,0,0,0,0,0,1,0,1243,0,0,0,1,2,0.0,0,0,0,0,5.5,True,0,0,1,2016-17

In [8]:
pd.read_csv(FPL_DATA_PATH + f'2016-17/cleaned_players.csv', encoding="ISO-8859-1").head()

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent
0,David,Ospina,0,0,2,143,4,0.0,28.8,0,0,18,2.9,0,0,0,0.2
1,Petr,Cech,0,0,134,3097,37,0.1,819.8,0,2,660,82.0,12,0,2,13.7
2,Laurent,Koscielny,2,1,121,2821,37,53.9,831.2,239,19,723,112.7,10,1,4,11.2
3,Per,Mertesacker,0,0,1,38,1,0.1,17.8,0,0,5,1.8,0,0,0,0.2
4,Gabriel Armando,de Abreu,0,0,45,1517,18,84.5,295.8,119,2,296,50.0,5,0,6,0.8

In [9]:
pd.read_csv(FPL_DATA_PATH + f'2016-17/player_idlist.csv', encoding="ISO-8859-1").head()

        first_name  second_name  id
0            David       Ospina   1
1             Petr         Cech   2
2          Laurent    Koscielny   3
3              Per  Mertesacker   4
4  Gabriel Armando     de Abreu   5

cleaned_player.csv and player_idlist.csv not useful!

In [10]:
players_raw = pd.read_csv(FPL_DATA_PATH + f'2016-17/players_raw.csv', encoding="ISO-8859-1")
players_raw.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,ea_index,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,id,in_dreamteam,influence,loaned_in,loaned_out,loans_in,loans_out,minutes,news,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,0,0,18,100,100,0,48844,0,0,-3,3,0.0,0,56,1,0.0,0.0,0,David,0.0,4,0,2.9,1,False,28.8,0,0,0,0,143,NaN,47,0,0,0,48844.jpg,1.0,0,4,Ospina,0.2,False,13,a,1,3,0.0,2,3433,0,7905,0,0.0,0.4,Ospina,0
1,0,2,660,100,100,12,11334,0,0,-1,1,0.1,0,409,1,6.0,0.0,4,Petr,0.0,37,0,82.0,2,False,819.8,0,0,0,0,3097,NaN,54,1,0,0,11334.jpg,3.8,0,115,Cech,13.7,False,33,a,1,3,0.0,134,432837,0,590727,0,0.0,24.8,Cech,2
2,1,19,723,0,75,10,51507,0,0,1,-1,53.9,3,493,2,1.7,0.0,-2,Laurent,0.0,37,2,112.7,3,False,831.2,0,0,0,0,2821,Suspended - unknown return date,61,0,0,0,51507.jpg,3.7,1,0,Koscielny,11.2,False,6,s,1,3,239.0,121,965040,0,857277,0,0.0,19.8,Koscielny,4
3,0,0,5,100,100,0,17127,0,0,-2,2,0.1,0,265,2,0.0,0.0,1,Per,0.0,1,0,1.8,4,False,17.8,0,0,0,0,38,NaN,48,0,0,0,17127.jpg,1.0,0,0,Mertesacker,0.2,False,4,a,1,3,0.0,1,2141,0,5912,0,0.0,0.2,Mertesacker,0
4,0,2,296,75,100,5,158074,0,0,-2,2,84.5,0,244,2,1.0,0.0,0,Gabriel Armando,0.0,18,0,50.0,5,False,295.8,0,0,0,0,1517,Knee injury - 75% chance of playing,48,0,0,0,158074.jpg,2.4,0,0,de Abreu,0.8,False,5,d,1,3,119.0,45,119600,0,100361,0,0.0,9.4,Gabriel,6

In [11]:
print(players_raw.shape)
(players_raw['first_name'] + players_raw['second_name']).nunique()

(683, 57)

683

Looks like data is for last GW only or aggregate

In [12]:
players_raw['team'].unique()

array([ 1, 12,  2,  4,  3,  5, 13,  6, 10, 18, 15,  7, 20, 19,  8,  9, 14,
       11, 16, 17])

In [13]:
players_raw['team_code'].unique()

array([  3,  25,  91,   8,  90,  31,  20,  11,  43,  57,  56,  88,  21,
        35,  13,  14, 110,   1,  80,   6])

In [14]:
players_raw['element_type'].unique()

array([1, 2, 3, 4])

In [15]:
POSITION_MAP = { # https://github.com/vaastav/Fantasy-Premier-League/issues/1
    1: 'GK',
    2: 'DEF',
    3: 'MID',
    4: 'FWD'
}
players_raw['element_type'] = players_raw['element_type'].map(POSITION_MAP)

players_raw.rename(columns={'element_type': 'position'}, inplace=True)

In [16]:
players_raw = players_raw.copy()[['first_name', 'second_name', 'team', 'position']]
players_raw['season'] = '2016-17'

In [17]:
team_data = pd.read_csv('data/external/team_season_data.csv')
team_data.head()

        team_name  team   season  promoted_side  top_6_last_season
0         Arsenal     1  2016-17              0                  1
1     Bournemouth     2  2016-17              0                  0
2         Burnley     3  2016-17              1                  0
3         Chelsea     4  2016-17              0                  0
4  Crystal Palace     5  2016-17              0                  0

In [18]:
for name in ['first_name', 'second_name']:
    players_raw[name] = players_raw[name].str.replace('√É¬©', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('√É¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬∫', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬º', 'u')
    players_raw[name] = players_raw[name].str.replace('√É¬Ø', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬≥', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬®', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∂', 'o')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬≠', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∏', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬±', 'n')
    players_raw[name] = players_raw[name].str.replace('√É¬•', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('i¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    
    players_raw[name] = players_raw[name].str.lower()
players_raw.head()

        first_name  second_name  team position   season
0            david       ospina     1       GK  2016-17
1             petr         cech     1       GK  2016-17
2          laurent    koscielny     1      DEF  2016-17
3              per  mertesacker     1      DEF  2016-17
4  gabriel armando     de abreu     1      DEF  2016-17

In [19]:
players_raw = players_raw.merge(team_data, on=['team', 'season'], how='left')
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season
0,david,ospina,1,GK,2016-17,Arsenal,0,1
1,petr,cech,1,GK,2016-17,Arsenal,0,1
2,laurent,koscielny,1,DEF,2016-17,Arsenal,0,1
3,per,mertesacker,1,DEF,2016-17,Arsenal,0,1
4,gabriel armando,de abreu,1,DEF,2016-17,Arsenal,0,1

In [20]:
players_raw['name'] = players_raw['first_name'] + '_' + players_raw['second_name']
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season,name
0,david,ospina,1,GK,2016-17,Arsenal,0,1,david_ospina
1,petr,cech,1,GK,2016-17,Arsenal,0,1,petr_cech
2,laurent,koscielny,1,DEF,2016-17,Arsenal,0,1,laurent_koscielny
3,per,mertesacker,1,DEF,2016-17,Arsenal,0,1,per_mertesacker
4,gabriel armando,de abreu,1,DEF,2016-17,Arsenal,0,1,gabriel armando_de abreu

In [21]:
gw_dataframe['name'] = gw_dataframe['name'].apply(lambda x: unidecode.unidecode(x))
gw_dataframe['name'] = gw_dataframe['name'].str.lower()

In [22]:
# Check that number of non-matches due to accents isn't too high
test = gw_dataframe.merge(players_raw, on=['name', 'season'], how='left')
no_matches = test[test['first_name'].isnull()]
assert no_matches['name'].nunique() / test['name'].nunique() < 0.05

In [23]:
gw_data_full_1617 = gw_dataframe.merge(players_raw, on=['name', 'season'], how='inner')
gw_data_full_1617.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,first_name,second_name,team,position,team_name,promoted_side,top_6_last_season
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15 20:00:00+01:00,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17,aaron,cresswell,20,DEF,West Ham United,0,0
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,20,0,0,0,0.0,979,0.0,0,2016-08-21 16:00:00+01:00,21 Aug 16:00,0,0,0,0,0,2,0,0,0,0,0,0,2,0,11531,0,0,0,0,1,0.0,0,-3002,79,3081,5.5,True,0,0,2,2016-17,aaron,cresswell,20,DEF,West Ham United,0,0
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,29,0,0,0,0.0,1519,0.0,0,2016-08-28 16:00:00+01:00,28 Aug 16:00,0,0,0,0,0,10,0,0,0,0,0,0,3,0,9587,0,0,0,1,3,0.0,0,-2053,28,2081,5.4,False,0,0,3,2016-17,aaron,cresswell,20,DEF,West Ham United,0,0
3,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,38,0,0,0,0.0,2069,0.0,0,2016-09-10 15:00:00+01:00,10 Sep 15:00,0,0,0,0,0,18,0,0,0,0,0,0,4,0,8427,0,0,0,4,2,0.0,0,-1221,45,1266,5.4,True,0,0,4,2016-17,aaron,cresswell,20,DEF,West Ham United,0,0
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,46,0,0,0,0.0,2650,0.0,0,2016-09-17 15:00:00+01:00,17 Sep 15:00,0,0,0,0,0,19,0,0,0,0,0,0,5,0,7933,0,0,0,2,4,0.0,0,-520,29,549,5.4,False,0,0,5,2016-17,aaron,cresswell,20,DEF,West Ham United,0,0

## 2017-18

In [24]:
pd.read_csv(FPL_DATA_PATH + '2017-18/gws/gw1.csv', encoding="ISO-8859-1").head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards
0,Aaron_Cresswell,0,10,0,0,0,3,0,0,9,0.6,0,0,443,0,0,9,0,2,0,1.9,443,0.4,0,2017-08-13T15:00:00Z,13 Aug 16:00,0,0,9,0,0,12,0,0,0,0,0,0,1,0,25136,0,0,0,0,4,18.0,0,0,0,0,50,False,0,0
1,Aaron_Lennon,0,0,0,0,0,0,0,0,0,0.0,0,0,153,0,0,5,0,0,0,0.0,153,0.0,0,2017-08-12T14:00:00Z,12 Aug 15:00,0,0,0,0,0,15,0,0,0,0,0,0,1,0,4681,0,0,0,0,1,0.0,0,0,0,0,55,True,0,0
2,Aaron_Mooy,1,52,0,0,0,22,1,5,41,46.9,0,0,172,0,0,4,0,0,0,8.7,172,40.2,3,2017-08-12T14:00:00Z,12 Aug 15:00,0,0,90,0,1,6,0,0,0,0,5,0,1,0,59955,2,0,0,3,0,0.0,6,0,0,0,55,False,0,0
3,Aaron_Ramsey,0,11,0,1,0,16,0,0,8,11.2,0,0,18,0,0,1,0,0,1,6.7,18,29.6,1,2017-08-11T18:45:00Z,11 Aug 19:45,0,0,23,0,0,9,0,0,0,0,2,0,1,0,33792,0,0,3,3,4,26.0,6,0,0,0,70,True,0,0
4,Abdoulaye_Doucour√©,0,73,0,0,2,36,0,3,60,25.2,3,0,414,0,0,7,2,3,1,10.9,414,48.6,2,2017-08-12T11:30:00Z,12 Aug 12:30,0,0,90,0,0,10,0,0,0,0,11,0,1,0,1207,1,1,0,3,3,35.0,9,0,0,0,50,True,0,0

In [25]:
gw_dataframe = pd.DataFrame()
for gw in range(1, 39):
    gw_data = pd.read_csv(FPL_DATA_PATH + f'2017-18/gws/gw{gw}.csv', encoding="ISO-8859-1")
    gw_data['gw'] = gw
    gw_data['season'] = '2017-18'
    gw_dataframe = gw_dataframe.append(gw_data)

In [26]:
gw_dataframe['value'] = gw_dataframe['value'] / 10

In [27]:
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].str.replace('T', ' ')
gw_dataframe['kickoff_time'] = pd.to_datetime(gw_dataframe['kickoff_time'])
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].dt.tz_convert('Europe/London')

In [28]:
gw_dataframe.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season
0,Aaron_Cresswell,0,10,0,0,0,3,0,0,9,0.6,0,0,443,0,0,9,0,2,0,1.9,443,0.4,0,2017-08-13 16:00:00+01:00,13 Aug 16:00,0,0,9,0,0,12,0,0,0,0,0,0,1,0,25136,0,0,0,0,4,18.0,0,0,0,0,5.0,False,0,0,1,2017-18
1,Aaron_Lennon,0,0,0,0,0,0,0,0,0,0.0,0,0,153,0,0,5,0,0,0,0.0,153,0.0,0,2017-08-12 15:00:00+01:00,12 Aug 15:00,0,0,0,0,0,15,0,0,0,0,0,0,1,0,4681,0,0,0,0,1,0.0,0,0,0,0,5.5,True,0,0,1,2017-18
2,Aaron_Mooy,1,52,0,0,0,22,1,5,41,46.9,0,0,172,0,0,4,0,0,0,8.7,172,40.2,3,2017-08-12 15:00:00+01:00,12 Aug 15:00,0,0,90,0,1,6,0,0,0,0,5,0,1,0,59955,2,0,0,3,0,0.0,6,0,0,0,5.5,False,0,0,1,2017-18
3,Aaron_Ramsey,0,11,0,1,0,16,0,0,8,11.2,0,0,18,0,0,1,0,0,1,6.7,18,29.6,1,2017-08-11 19:45:00+01:00,11 Aug 19:45,0,0,23,0,0,9,0,0,0,0,2,0,1,0,33792,0,0,3,3,4,26.0,6,0,0,0,7.0,True,0,0,1,2017-18
4,Abdoulaye_Doucour√©,0,73,0,0,2,36,0,3,60,25.2,3,0,414,0,0,7,2,3,1,10.9,414,48.6,2,2017-08-12 12:30:00+01:00,12 Aug 12:30,0,0,90,0,0,10,0,0,0,0,11,0,1,0,1207,1,1,0,3,3,35.0,9,0,0,0,5.0,True,0,0,1,2017-18

In [29]:
gw_dataframe.shape

(22467, 57)

__Player data__

In [30]:
players_raw = pd.read_csv(FPL_DATA_PATH + f'2017-18/players_raw.csv', encoding="ISO-8859-1")
players_raw.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,ea_index,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,id,in_dreamteam,influence,loaned_in,loaned_out,loans_in,loans_out,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,0,1,86,100,100,2,48844,0,0,-2,2,0.0,0,0,1,1.8,3.0,8,David,2.0,3,0,7.7,1,False,75.8,0,0,0,0,380,NaN,2018-04-29T20:01:18Z,48,0,0,0,48844.jpg,3.8,0,9,Ospina,0.2,False,13,a,1,3,0.0,19,3948,0,10172,0,0.4,4.0,Ospina,0
1,0,7,627,100,100,11,11334,0,0,-2,2,0.0,1,0,1,3.0,2.7,0,Petr,1.7,48,0,71.9,2,False,722.4,0,0,0,0,3039,NaN,2018-04-22T12:01:20Z,53,0,0,1,11334.jpg,3.6,0,90,Cech,4.5,False,33,a,1,3,0.0,124,183262,0,294471,0,0.3,23.4,Cech,1
2,0,0,0,0,0,0,98980,0,0,0,0,0.0,0,0,1,0.0,0.0,0,Damian Emiliano,0.0,0,0,0.0,3,False,0.0,0,0,0,0,0,Season-long loan to Getafe,2017-08-03T08:35:02Z,40,0,0,0,98980.jpg,0.0,0,0,Martinez,0.6,False,26,u,1,3,0.0,0,1506,0,29335,0,0.0,0.0,Martinez,0
3,0,16,556,0,0,9,51507,0,0,0,0,123.8,3,0,2,0.0,0.0,0,Laurent,0.3,32,2,95.5,4,False,692.0,0,0,0,0,2225,Achilles injury - Unknown return date,2018-05-03T21:31:18Z,60,0,0,0,51507.jpg,4.0,0,0,Koscielny,1.5,False,6,i,1,3,137.0,100,205878,0,199153,0,0.1,16.7,Koscielny,4
4,0,2,81,100,100,0,17127,0,0,-3,3,3.0,1,0,2,1.2,1.2,0,Per,0.2,7,1,16.1,5,False,119.6,0,0,0,0,364,NaN,2017-11-18T12:31:16Z,47,0,0,0,17127.jpg,2.7,0,0,Mertesacker,0.5,False,4,a,1,3,38.0,16,31711,0,46441,0,0.0,3.4,Mertesacker,0

In [31]:
POSITION_MAP = { # https://github.com/vaastav/Fantasy-Premier-League/issues/1
    1: 'GK',
    2: 'DEF',
    3: 'MID',
    4: 'FWD'
}
players_raw['element_type'] = players_raw['element_type'].map(POSITION_MAP)

players_raw.rename(columns={'element_type': 'position'}, inplace=True)

In [32]:
players_raw = players_raw.copy()[['first_name', 'second_name', 'team', 'position']]
players_raw['season'] = '2017-18'

In [33]:
team_data = pd.read_csv('data/external/team_season_data.csv')
team_data.head()

        team_name  team   season  promoted_side  top_6_last_season
0         Arsenal     1  2016-17              0                  1
1     Bournemouth     2  2016-17              0                  0
2         Burnley     3  2016-17              1                  0
3         Chelsea     4  2016-17              0                  0
4  Crystal Palace     5  2016-17              0                  0

In [34]:
for name in ['first_name', 'second_name']:
    players_raw[name] = players_raw[name].str.replace('√É¬©', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('√É¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬∫', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬º', 'u')
    players_raw[name] = players_raw[name].str.replace('√É¬Ø', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬≥', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬®', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∂', 'o')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬≠', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∏', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬±', 'n')
    players_raw[name] = players_raw[name].str.replace('√É¬•', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('i¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    
    
    players_raw[name] = players_raw[name].str.lower()
players_raw.head()

        first_name  second_name  team position   season
0            david       ospina     1       GK  2017-18
1             petr         cech     1       GK  2017-18
2  damian emiliano     martinez     1       GK  2017-18
3          laurent    koscielny     1      DEF  2017-18
4              per  mertesacker     1      DEF  2017-18

In [35]:
players_raw = players_raw.merge(team_data, on=['team', 'season'], how='left')
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season
0,david,ospina,1,GK,2017-18,Arsenal,0,1
1,petr,cech,1,GK,2017-18,Arsenal,0,1
2,damian emiliano,martinez,1,GK,2017-18,Arsenal,0,1
3,laurent,koscielny,1,DEF,2017-18,Arsenal,0,1
4,per,mertesacker,1,DEF,2017-18,Arsenal,0,1

In [36]:
players_raw['name'] = players_raw['first_name'] + '_' + players_raw['second_name']
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season,name
0,david,ospina,1,GK,2017-18,Arsenal,0,1,david_ospina
1,petr,cech,1,GK,2017-18,Arsenal,0,1,petr_cech
2,damian emiliano,martinez,1,GK,2017-18,Arsenal,0,1,damian emiliano_martinez
3,laurent,koscielny,1,DEF,2017-18,Arsenal,0,1,laurent_koscielny
4,per,mertesacker,1,DEF,2017-18,Arsenal,0,1,per_mertesacker

In [37]:
gw_dataframe['name'] = gw_dataframe['name'].apply(lambda x: unidecode.unidecode(x))
gw_dataframe['name'] = gw_dataframe['name'].str.lower()

In [38]:
# Check that number of non-matches due to accents isn't too high
test = gw_dataframe.merge(players_raw, on=['name', 'season'], how='left')
no_matches = test[test['first_name'].isnull()]
assert no_matches['name'].nunique() / test['name'].nunique() < 0.05

In [39]:
gw_data_full_1718 = gw_dataframe.merge(players_raw, on=['name', 'season'], how='inner')
gw_data_full_1718.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,first_name,second_name,team,position,team_name,promoted_side,top_6_last_season
0,aaron_cresswell,0,10,0,0,0,3,0,0,9,0.6,0,0,443,0,0,9,0,2,0,1.9,443,0.4,0,2017-08-13 16:00:00+01:00,13 Aug 16:00,0,0,9,0,0,12,0,0,0,0,0,0,1,0,25136,0,0,0,0,4,18.0,0,0,0,0,5.0,False,0,0,1,2017-18,aaron,cresswell,20,DEF,West Ham United,0,0
1,aaron_cresswell,0,21,0,0,0,16,0,6,17,52.9,0,0,443,0,0,15,0,3,0,7.4,954,21.2,4,2017-08-19 15:00:00+01:00,19 Aug 15:00,0,0,90,0,3,14,0,0,0,0,2,0,2,0,27824,0,0,0,2,3,0.0,1,-1515,945,2460,5.0,False,0,0,2,2017-18,aaron,cresswell,20,DEF,West Ham United,0,0
2,aaron_cresswell,0,43,0,0,0,11,0,4,36,1.6,0,0,443,0,0,26,1,3,0,2.4,1470,11.2,0,2017-08-26 15:00:00+01:00,26 Aug 15:00,0,0,90,0,0,13,0,0,0,0,3,0,3,0,28464,0,0,1,0,3,11.0,1,-269,2323,2592,5.0,False,0,0,3,2017-18,aaron,cresswell,20,DEF,West Ham United,0,0
3,aaron_cresswell,0,22,1,0,0,23,1,3,14,47.1,0,0,443,0,0,40,1,0,0,6.2,2001,14.2,3,2017-09-11 20:00:00+01:00,11 Sep 20:00,0,0,90,0,2,8,0,0,0,0,4,0,4,0,28977,3,0,1,0,2,1.0,6,-338,2793,3131,5.0,True,0,0,4,2017-18,aaron,cresswell,20,DEF,West Ham United,0,0
4,aaron_cresswell,0,30,0,0,3,30,1,4,27,34.3,0,0,443,0,0,48,0,0,0,4.6,2545,11.2,2,2017-09-16 15:00:00+01:00,16 Sep 15:00,0,0,90,0,1,19,0,0,0,0,4,0,5,0,30355,0,0,0,0,0,0.0,9,905,3136,2231,5.0,False,0,0,5,2017-18,aaron,cresswell,20,DEF,West Ham United,0,0

## 2018-19

In [40]:
pd.read_csv(FPL_DATA_PATH + '2018-19/gws/gw1.csv', encoding="ISO-8859-1").head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards
0,Aaron_Cresswell_402,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,5,0,0,0,0.0,402,0.0,0,2018-08-12T12:30:00Z,12 Aug 13:30,0,0,0,0,0,12,0,0,0,0,0,0,1,0,103396,0,0,0,0,4,0.0,0,0,0,0,55,False,0,0
1,Aaron_Lennon_83,0,22,0,1,0,6,1,1,17,12.3,0,0,83,0,0,8,1,0,0,3.9,83,10.0,0,2018-08-12T12:30:00Z,12 Aug 13:30,0,0,90,0,1,16,0,0,0,0,2,0,1,0,15138,1,2,0,0,0,17.0,3,0,0,0,50,False,0,0
2,Aaron_Mooy_199,0,51,0,0,0,24,0,2,40,18.2,1,0,199,0,0,4,1,3,0,3.8,199,20.2,1,2018-08-11T14:00:00Z,11 Aug 15:00,0,0,90,0,0,6,0,0,0,0,11,0,1,0,192110,1,6,0,3,0,0.0,2,0,0,0,55,True,0,0
3,Aaron_Ramsey_14,0,11,0,0,0,7,0,0,7,10.8,1,0,14,0,0,1,0,1,0,2.9,14,9.4,1,2018-08-12T15:00:00Z,12 Aug 16:00,0,0,53,2,0,13,0,0,0,0,1,0,1,0,60423,0,2,0,2,0,9.0,1,0,0,0,75,True,0,0
4,Aaron_Wan-Bissaka_145,1,29,1,0,3,38,1,11,19,14.0,2,0,145,0,0,3,0,0,0,6.0,145,46.0,1,2018-08-11T14:00:00Z,11 Aug 15:00,0,0,90,0,0,9,0,0,0,0,7,0,1,0,652304,2,0,0,2,0,0.0,12,0,0,0,40,False,0,0

In [41]:
gw_dataframe = pd.DataFrame()
for gw in range(1, 39):
    gw_data = pd.read_csv(FPL_DATA_PATH + f'2018-19/gws/gw{gw}.csv', encoding="ISO-8859-1")
    gw_data['gw'] = gw
    gw_data['season'] = '2018-19'
    gw_dataframe = gw_dataframe.append(gw_data)

In [42]:
gw_dataframe['value'] = gw_dataframe['value'] / 10

In [43]:
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].str.replace('T', ' ')
gw_dataframe['kickoff_time'] = pd.to_datetime(gw_dataframe['kickoff_time'])
gw_dataframe['kickoff_time'] = gw_dataframe['kickoff_time'].dt.tz_convert('Europe/London')

In [44]:
gw_dataframe.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season
0,Aaron_Cresswell_402,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,5,0,0,0,0.0,402,0.0,0,2018-08-12 13:30:00+01:00,12 Aug 13:30,0,0,0,0,0,12,0,0,0,0,0,0,1,0,103396,0,0,0,0,4,0.0,0,0,0,0,5.5,False,0,0,1,2018-19
1,Aaron_Lennon_83,0,22,0,1,0,6,1,1,17,12.3,0,0,83,0,0,8,1,0,0,3.9,83,10.0,0,2018-08-12 13:30:00+01:00,12 Aug 13:30,0,0,90,0,1,16,0,0,0,0,2,0,1,0,15138,1,2,0,0,0,17.0,3,0,0,0,5.0,False,0,0,1,2018-19
2,Aaron_Mooy_199,0,51,0,0,0,24,0,2,40,18.2,1,0,199,0,0,4,1,3,0,3.8,199,20.2,1,2018-08-11 15:00:00+01:00,11 Aug 15:00,0,0,90,0,0,6,0,0,0,0,11,0,1,0,192110,1,6,0,3,0,0.0,2,0,0,0,5.5,True,0,0,1,2018-19
3,Aaron_Ramsey_14,0,11,0,0,0,7,0,0,7,10.8,1,0,14,0,0,1,0,1,0,2.9,14,9.4,1,2018-08-12 16:00:00+01:00,12 Aug 16:00,0,0,53,2,0,13,0,0,0,0,1,0,1,0,60423,0,2,0,2,0,9.0,1,0,0,0,7.5,True,0,0,1,2018-19
4,Aaron_Wan-Bissaka_145,1,29,1,0,3,38,1,11,19,14.0,2,0,145,0,0,3,0,0,0,6.0,145,46.0,1,2018-08-11 15:00:00+01:00,11 Aug 15:00,0,0,90,0,0,9,0,0,0,0,7,0,1,0,652304,2,0,0,2,0,0.0,12,0,0,0,4.0,False,0,0,1,2018-19

In [45]:
gw_dataframe['name'] = gw_dataframe['name'].str.replace(r"_(\d+)", "")  # remove trailing _number
gw_dataframe.head(2)

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,5,0,0,0,0.0,402,0.0,0,2018-08-12 13:30:00+01:00,12 Aug 13:30,0,0,0,0,0,12,0,0,0,0,0,0,1,0,103396,0,0,0,0,4,0.0,0,0,0,0,5.5,False,0,0,1,2018-19
1,Aaron_Lennon,0,22,0,1,0,6,1,1,17,12.3,0,0,83,0,0,8,1,0,0,3.9,83,10.0,0,2018-08-12 13:30:00+01:00,12 Aug 13:30,0,0,90,0,1,16,0,0,0,0,2,0,1,0,15138,1,2,0,0,0,17.0,3,0,0,0,5.0,False,0,0,1,2018-19

__Player data__

In [46]:
players_raw = pd.read_csv(FPL_DATA_PATH + f'2018-19/players_raw.csv', encoding="ISO-8859-1")
players_raw.head()

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,ea_index,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,id,in_dreamteam,influence,loaned_in,loaned_out,loans_in,loans_out,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,0,3,130,100,100,1,11334,0,0,-3,3,0.0,0,0,1,0.5,0.5,0,Petr,0.0,9,0,20.4,1,False,205.0,0,0,0,0,585,NaN,2018-09-29T17:31:14Z,47,0,0,0,11334.jpg,3.4,0,27,Cech,1.1,False,1,a,1,3,0.0,24,83497,0,136211,0,0.0,5.1,Cech,0
1,0,5,568,None,None,6,80201,0,0,-1,1,0.0,1,0,1,3.7,3.7,3,Bernd,3.2,42,0,80.5,2,False,807.2,0,0,0,0,2835,NaN,None,49,0,0,0,80201.jpg,3.3,0,105,Leno,4.0,False,19,a,1,3,0.0,106,339095,0,250834,0,0.7,21.6,Leno,0
2,0,8,319,100,100,3,51507,0,0,-1,1,29.5,1,0,2,2.7,2.5,1,Laurent,2.0,23,3,59.1,3,False,456.4,0,0,0,0,1329,NaN,2019-05-03T08:31:19Z,54,0,0,0,51507.jpg,3.6,0,0,Koscielny,0.9,False,6,a,1,3,105.0,62,128478,0,92187,0,0.4,11.5,Koscielny,1
3,5,5,304,0,0,4,98745,0,0,-2,2,197.8,0,0,2,0.0,0.0,0,H√É¬©ctor,0.0,21,0,73.7,4,False,261.6,0,0,0,0,1532,Knee injury - Unknown return date,2019-01-19T20:01:19Z,53,1,0,0,98745.jpg,3.2,0,0,Beller√É¬≠n,4.5,False,2,i,1,3,280.0,60,567084,0,1143684,0,0.0,11.3,Beller√É¬≠n,3
4,4,7,392,100,100,5,38411,0,0,-1,1,196.6,1,0,2,3.3,3.2,2,Nacho,2.7,24,1,83.4,5,False,413.2,0,0,0,0,1860,NaN,2019-04-28T10:31:25Z,54,0,0,0,38411.jpg,3.5,0,0,Monreal,1.3,False,18,a,1,3,224.0,77,298216,0,290921,0,0.5,14.3,Monreal,5

In [47]:
POSITION_MAP = { # https://github.com/vaastav/Fantasy-Premier-League/issues/1
    1: 'GK',
    2: 'DEF',
    3: 'MID',
    4: 'FWD'
}
players_raw['element_type'] = players_raw['element_type'].map(POSITION_MAP)

players_raw.rename(columns={'element_type': 'position'}, inplace=True)

In [48]:
players_raw = players_raw[['first_name', 'second_name', 'team', 'position']]
players_raw['season'] = '2018-19'

In [49]:
team_data = pd.read_csv('data/external/team_season_data.csv')
team_data.head()

        team_name  team   season  promoted_side  top_6_last_season
0         Arsenal     1  2016-17              0                  1
1     Bournemouth     2  2016-17              0                  0
2         Burnley     3  2016-17              1                  0
3         Chelsea     4  2016-17              0                  0
4  Crystal Palace     5  2016-17              0                  0

In [50]:
for name in ['first_name', 'second_name']:
    players_raw[name] = players_raw[name].str.replace('√É¬©', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('√É¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬∫', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬º', 'u')
    players_raw[name] = players_raw[name].str.replace('√É¬Ø', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬≥', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬®', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∂', 'o')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬≠', 'i')
    players_raw[name] = players_raw[name].str.replace('√É¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('√É¬∏', 'o')
    players_raw[name] = players_raw[name].str.replace('√É¬±', 'n')
    players_raw[name] = players_raw[name].str.replace('√É¬•', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬´', 'e')
    players_raw[name] = players_raw[name].str.replace('i¬°', 'a')
    players_raw[name] = players_raw[name].str.replace('i¬ñ', 'o')
    #
    players_raw[name] = players_raw[name].str.replace('√É¬£', 'a')
    players_raw[name] = players_raw[name].str.replace('√É¬ß', 'c')
    players_raw[name] = players_raw[name].str.replace('√É¬§', 'a')
    
    players_raw[name] = players_raw[name].str.lower()
players_raw.head()

  first_name second_name  team position   season
0       petr        cech     1       GK  2018-19
1      bernd        leno     1       GK  2018-19
2    laurent   koscielny     1      DEF  2018-19
3     hector    bellerin     1      DEF  2018-19
4      nacho     monreal     1      DEF  2018-19

In [51]:
players_raw = players_raw.merge(team_data, on=['team', 'season'], how='left')
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season
0,petr,cech,1,GK,2018-19,Arsenal,0,1
1,bernd,leno,1,GK,2018-19,Arsenal,0,1
2,laurent,koscielny,1,DEF,2018-19,Arsenal,0,1
3,hector,bellerin,1,DEF,2018-19,Arsenal,0,1
4,nacho,monreal,1,DEF,2018-19,Arsenal,0,1

In [52]:
players_raw['name'] = players_raw['first_name'] + '_' + players_raw['second_name']
players_raw.head()

,first_name,second_name,team,position,season,team_name,promoted_side,top_6_last_season,name
0,petr,cech,1,GK,2018-19,Arsenal,0,1,petr_cech
1,bernd,leno,1,GK,2018-19,Arsenal,0,1,bernd_leno
2,laurent,koscielny,1,DEF,2018-19,Arsenal,0,1,laurent_koscielny
3,hector,bellerin,1,DEF,2018-19,Arsenal,0,1,hector_bellerin
4,nacho,monreal,1,DEF,2018-19,Arsenal,0,1,nacho_monreal

In [53]:
gw_dataframe['name'] = gw_dataframe['name'].apply(lambda x: unidecode.unidecode(x))
gw_dataframe['name'] = gw_dataframe['name'].str.lower()

In [54]:
# Check that number of non-matches due to accents isn't too high
test = gw_dataframe.merge(players_raw, on=['name', 'season'], how='left')
no_matches = test[test['first_name'].isnull()]
assert no_matches['name'].nunique() / test['name'].nunique() < 0.05

In [55]:
gw_data_full_1819 = gw_dataframe.merge(players_raw, on=['name', 'season'], how='inner')
gw_data_full_1819.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,first_name,second_name,team,position,team_name,promoted_side,top_6_last_season
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,5,0,0,0,0.0,402,0.0,0,2018-08-12 13:30:00+01:00,12 Aug 13:30,0,0,0,0,0,12,0,0,0,0,0,0,1,0,103396,0,0,0,0,4,0.0,0,0,0,0,5.5,False,0,0,1,2018-19,aaron,cresswell,19,DEF,West Ham United,0,0
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,20,0,0,0,0.0,927,0.0,0,2018-08-18 15:00:00+01:00,18 Aug 15:00,0,0,0,0,0,2,0,0,0,0,0,0,2,0,91333,0,0,0,2,1,0.0,0,-14496,933,15429,5.5,True,0,0,2,2018-19,aaron,cresswell,19,DEF,West Ham United,0,0
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,21,0,0,0,0.0,1454,0.0,0,2018-08-25 15:00:00+01:00,25 Aug 15:00,0,0,0,0,0,1,0,0,0,0,0,0,3,0,69306,0,0,0,1,3,0.0,0,-22473,246,22719,5.4,False,0,0,3,2018-19,aaron,cresswell,19,DEF,West Ham United,0,0
3,aaron_cresswell,0,47,0,0,0,10,0,1,39,27.6,0,0,402,0,0,40,1,1,0,3.7,1985,9.8,2,2018-09-01 15:00:00+01:00,01 Sep 15:00,0,0,90,0,1,20,0,0,0,0,4,0,4,0,57685,0,0,0,1,0,0.0,1,-12459,275,12734,5.3,True,0,1,4,2018-19,aaron,cresswell,19,DEF,West Ham United,0,0
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,402,0,0,43,0,0,0,0.0,2522,0.0,0,2018-09-16 16:00:00+01:00,16 Sep 16:00,0,0,0,0,0,8,0,0,0,0,0,0,5,0,51987,0,0,0,3,1,0.0,0,-6122,245,6367,5.3,False,0,0,5,2018-19,aaron,cresswell,19,DEF,West Ham United,0,0

In [56]:
fpl_data_all_seasons = pd.DataFrame()
for df in [gw_data_full_1617, gw_data_full_1718, gw_data_full_1819]:
    fpl_data_all_seasons = fpl_data_all_seasons.append(df)

In [57]:
fpl_data_all_seasons.shape

(67320, 64)

__Get player position dummies__

In [58]:
fpl_data_all_seasons = pd.get_dummies(fpl_data_all_seasons, columns=['position'])

__Get opponent team data__

In [59]:
team_data.head()

        team_name  team   season  promoted_side  top_6_last_season
0         Arsenal     1  2016-17              0                  1
1     Bournemouth     2  2016-17              0                  0
2         Burnley     3  2016-17              1                  0
3         Chelsea     4  2016-17              0                  0
4  Crystal Palace     5  2016-17              0                  0

In [60]:
fpl_data_all_seasons = fpl_data_all_seasons.merge(
    team_data,
    left_on=['opponent_team', 'season'],
    right_on=['team', 'season'],
    suffixes=('', '_opponent'),
    how='left'
)

In [61]:
fpl_data_all_seasons.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,first_name,second_name,team,team_name,promoted_side,top_6_last_season,position_DEF,position_FWD,position_GK,position_MID,team_name_opponent,team_opponent,promoted_side_opponent,top_6_last_season_opponent
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15 20:00:00+01:00,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Chelsea,4,0,0
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,20,0,0,0,0.0,979,0.0,0,2016-08-21 16:00:00+01:00,21 Aug 16:00,0,0,0,0,0,2,0,0,0,0,0,0,2,0,11531,0,0,0,0,1,0.0,0,-3002,79,3081,5.5,True,0,0,2,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Bournemouth,2,0,0
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,29,0,0,0,0.0,1519,0.0,0,2016-08-28 16:00:00+01:00,28 Aug 16:00,0,0,0,0,0,10,0,0,0,0,0,0,3,0,9587,0,0,0,1,3,0.0,0,-2053,28,2081,5.4,False,0,0,3,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Manchester City,10,0,1
3,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,38,0,0,0,0.0,2069,0.0,0,2016-09-10 15:00:00+01:00,10 Sep 15:00,0,0,0,0,0,18,0,0,0,0,0,0,4,0,8427,0,0,0,4,2,0.0,0,-1221,45,1266,5.4,True,0,0,4,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Watford,18,0,0
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,46,0,0,0,0.0,2650,0.0,0,2016-09-17 15:00:00+01:00,17 Sep 15:00,0,0,0,0,0,19,0,0,0,0,0,0,5,0,7933,0,0,0,2,4,0.0,0,-520,29,549,5.4,False,0,0,5,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,West Bromwich Albion,19,0,0

__Create features from kick-off time__

In [62]:
fpl_data_all_seasons['kickoff_month'] = fpl_data_all_seasons['kickoff_time'].dt.strftime("%b")
fpl_data_all_seasons = pd.get_dummies(fpl_data_all_seasons, columns=['kickoff_month'])

In [63]:
fpl_data_all_seasons['kickoff_hour'] = fpl_data_all_seasons['kickoff_time'].dt.hour

fpl_data_all_seasons['late_kickoff'] = np.where(
    fpl_data_all_seasons['kickoff_hour'] >= 17,
    1,
    0
)

fpl_data_all_seasons['early_kickoff'] = np.where(
    fpl_data_all_seasons['kickoff_hour'] <= 13,
    1,
    0
)

fpl_data_all_seasons.drop(columns=['kickoff_hour'], axis=1, inplace=True)

In [64]:
fpl_data_all_seasons.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,element,errors_leading_to_goal,errors_leading_to_goal_attempt,fixture,fouls,goals_conceded,goals_scored,ict_index,id,influence,key_passes,kickoff_time,kickoff_time_formatted,loaned_in,loaned_out,minutes,offside,open_play_crosses,opponent_team,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,round,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,first_name,second_name,team,team_name,promoted_side,top_6_last_season,position_DEF,position_FWD,position_GK,position_MID,team_name_opponent,team_opponent,promoted_side_opponent,top_6_last_season_opponent,kickoff_month_Apr,kickoff_month_Aug,kickoff_month_Dec,kickoff_month_Feb,kickoff_month_Jan,kickoff_month_Mar,kickoff_month_May,kickoff_month_Nov,kickoff_month_Oct,kickoff_month_Sep,late_kickoff,early_kickoff
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,10,0,0,0,0.0,454,0.0,0,2016-08-15 20:00:00+01:00,15 Aug 20:00,0,0,0,0,0,4,0,0,0,0,0,0,1,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Chelsea,4,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,20,0,0,0,0.0,979,0.0,0,2016-08-21 16:00:00+01:00,21 Aug 16:00,0,0,0,0,0,2,0,0,0,0,0,0,2,0,11531,0,0,0,0,1,0.0,0,-3002,79,3081,5.5,True,0,0,2,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Bournemouth,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,29,0,0,0,0.0,1519,0.0,0,2016-08-28 16:00:00+01:00,28 Aug 16:00,0,0,0,0,0,10,0,0,0,0,0,0,3,0,9587,0,0,0,1,3,0.0,0,-2053,28,2081,5.4,False,0,0,3,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Manchester City,10,0,1,0,1,0,0,0,0,0,0,0,0,0,0
3,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,38,0,0,0,0.0,2069,0.0,0,2016-09-10 15:00:00+01:00,10 Sep 15:00,0,0,0,0,0,18,0,0,0,0,0,0,4,0,8427,0,0,0,4,2,0.0,0,-1221,45,1266,5.4,True,0,0,4,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,Watford,18,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,454,0,0,46,0,0,0,0.0,2650,0.0,0,2016-09-17 15:00:00+01:00,17 Sep 15:00,0,0,0,0,0,19,0,0,0,0,0,0,5,0,7933,0,0,0,2,4,0.0,0,-520,29,549,5.4,False,0,0,5,2016-17,aaron,cresswell,20,West Ham United,0,0,1,0,0,0,West Bromwich Albion,19,0,0,0,0,0,0,0,0,0,0,0,1,0,0

__Drop irrelevant/unknown features__

In [65]:
COLUMNS_TO_DROP = ['element', 'fixture', 'id', 'kickoff_time', 'kickoff_time_formatted', 'opponent_team', 'round', 'first_name', 'second_name', 'team', 'team_opponent']

fpl_data_all_seasons.drop(
    columns=COLUMNS_TO_DROP,
    axis=1,
    inplace=True
)

__Create unique ID for each player__

In [66]:
id_df = fpl_data_all_seasons.groupby(['name']).count().reset_index()[['name']]
id_df['ID'] = id_df.index + 1
print(id_df.shape)
id_df.head()

(1075, 2)

              name  ID
0  aaron_cresswell   1
1     aaron_lennon   2
2       aaron_mooy   3
3   aaron_ramsdale   4
4     aaron_ramsey   5

In [67]:
fpl_data_all_seasons = fpl_data_all_seasons.merge(id_df, how='left', on=['name'])

In [68]:
fpl_data_all_seasons.head()

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,errors_leading_to_goal,errors_leading_to_goal_attempt,fouls,goals_conceded,goals_scored,ict_index,influence,key_passes,loaned_in,loaned_out,minutes,offside,open_play_crosses,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,team_name,promoted_side,top_6_last_season,position_DEF,position_FWD,position_GK,position_MID,team_name_opponent,promoted_side_opponent,top_6_last_season_opponent,kickoff_month_Apr,kickoff_month_Aug,kickoff_month_Dec,kickoff_month_Feb,kickoff_month_Jan,kickoff_month_Mar,kickoff_month_May,kickoff_month_Nov,kickoff_month_Oct,kickoff_month_Sep,late_kickoff,early_kickoff,ID
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17,West Ham United,0,0,1,0,0,0,Chelsea,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,11531,0,0,0,0,1,0.0,0,-3002,79,3081,5.5,True,0,0,2,2016-17,West Ham United,0,0,1,0,0,0,Bournemouth,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,9587,0,0,0,1,3,0.0,0,-2053,28,2081,5.4,False,0,0,3,2016-17,West Ham United,0,0,1,0,0,0,Manchester City,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1
3,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,8427,0,0,0,4,2,0.0,0,-1221,45,1266,5.4,True,0,0,4,2016-17,West Ham United,0,0,1,0,0,0,Watford,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,7933,0,0,0,2,4,0.0,0,-520,29,549,5.4,False,0,0,5,2016-17,West Ham United,0,0,1,0,0,0,West Bromwich Albion,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1

In [69]:
print(fpl_data_all_seasons.shape)
fpl_data_all_seasons.head()

(67320, 73)

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,creativity,dribbles,ea_index,errors_leading_to_goal,errors_leading_to_goal_attempt,fouls,goals_conceded,goals_scored,ict_index,influence,key_passes,loaned_in,loaned_out,minutes,offside,open_play_crosses,own_goals,penalties_conceded,penalties_missed,penalties_saved,recoveries,red_cards,saves,selected,tackled,tackles,target_missed,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,gw,season,team_name,promoted_side,top_6_last_season,position_DEF,position_FWD,position_GK,position_MID,team_name_opponent,promoted_side_opponent,top_6_last_season_opponent,kickoff_month_Apr,kickoff_month_Aug,kickoff_month_Dec,kickoff_month_Feb,kickoff_month_Jan,kickoff_month_Mar,kickoff_month_May,kickoff_month_Nov,kickoff_month_Oct,kickoff_month_Sep,late_kickoff,early_kickoff,ID
0,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,14023,0,0,0,1,2,0.0,0,0,0,0,5.5,False,0,0,1,2016-17,West Ham United,0,0,1,0,0,0,Chelsea,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1
1,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,11531,0,0,0,0,1,0.0,0,-3002,79,3081,5.5,True,0,0,2,2016-17,West Ham United,0,0,1,0,0,0,Bournemouth,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,9587,0,0,0,1,3,0.0,0,-2053,28,2081,5.4,False,0,0,3,2016-17,West Ham United,0,0,1,0,0,0,Manchester City,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1
3,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,8427,0,0,0,4,2,0.0,0,-1221,45,1266,5.4,True,0,0,4,2016-17,West Ham United,0,0,1,0,0,0,Watford,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
4,aaron_cresswell,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,7933,0,0,0,2,4,0.0,0,-520,29,549,5.4,False,0,0,5,2016-17,West Ham United,0,0,1,0,0,0,West Bromwich Albion,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1

In [68]:
fpl_data_all_seasons.to_parquet('data/processed/fpl_data_all_seasons.parquet', index=False)